### ISSUE TITLE
l2 might be not defined

### ISSUE THREAD

**Issue by Jarvx** [acq4/acq4#119]
https://github.com/acq4/acq4/blob/fda1d85947a7d424afe3b45538b394db6d5ad465/acq4/devices/Scanner/optimize.py#L142

I feel like l2 is not available if the "last" is not None (line 139).

**Comment by campagnola** [comment]
`opt2` is written such that the last item it yields contains `(order, None)` : https://github.com/acq4/acq4/blob/fda1d85947a7d424afe3b45538b394db6d5ad465/acq4/devices/Scanner/optimize.py#L68

**Comment by campagnola** [comment]
@Jarvx are you a robot?

**Comment by Jarvx** [comment]
> @Jarvx are you a robot?

Thanks for the response and the patience,  I was just searching the resources and read your code.
