### ISSUE TITLE
MulticlampTelegraph Auxiliary / priSignal / secSignal

### ISSUE THREAD

**Issue by pbmanis** [acq4/acq4#138]
This is an FYI regarding a strange issue. 

### Problem: 
Yesterday (5/19/2022), after several years of working, including on the previous day, acq4 on _one_ of the rigs (Rig 4 - Luke knows what this means) threw an exception at line 224 of `acq4/drivers/MultiClamp/MultiClampTelegraph.py`. The line sets `priSignal = "Auxiliary"`. Strangely, all other references to `Auxiliary` in the codebase and cache files seem to have a 1 or 2 appended to them, for example, `"Auxiliary1"`. Replacing the line with `priSignal = "Auxiliary1"` (and on 229, `secSignal = "Auxiliary2"`) fixed the problem. The caches had not been regenerated (the timestamp on the files is several years ago) and no other updates were evident, although I would not rule that out completely. This rig is the last one running Python2.7.  The amplifier is a 700B. 

I checked Rig 2, which is running a more recent Python3 version of acq4, and the code in that part of `MultiClampTelegraph.py` has not changed (line 224 says `priSignal = "Auxiliary"`. It works correctly as is, and the amplifier is a 700B.
Often when this happens I look at the `config/devices.cfg` configuration file first, but nothing had changed there either.

### Solution:
Changing line 224 to read `priSignal = "Auxiliary1"` (and on line 229, `secSignal = "Auxiliary2"`) removed the exception, and all acquisitions appeared to proceed normally. 

### Note:
In `acq4/drivers/multiclamp.py`, on lines 557 and 566, the variable in the  dictionary ['VC']['PRI'] is `"Auxiliaryl"` (ends wtih the letter "l", rather than the number `"1"`); whereas in ['VC']['PRI'] it reads `"Auxiliary2"`, which appears to be correct. I don't think this is related, but it may be something to look into.

**Comment by campagnola** [comment]
Hi Paul! 
I was able to confirm this today with a 700B and py3. I see an error if I have a task runner open with the clamp device selected, and then try to switch to one of the aux channels in current clamp -- this causes the clamp to report that it is using the "Auxiliary" channel, which is unrecognized by the taskrunner UI.

I pushed to the `main` branch: https://github.com/acq4/acq4/commit/8f2886310b833cf024f5b168d871533b79ac60e1
The correct names should be "Auxiliary 1" and "Auxiliary 2". There's a related commander bug here that prevents us knowing which aux signal is selected, so even if you have aux2 selected, the task runner ui will still report that aux1 is selected.

Thanks!

**Comment by pbmanis** [comment]
Hi Luke,
That was fast, and all makes sense. A quick check of the rig shows that the operator (not me...) had selected the Auxiliary output in the Commander for the "secondary output". Probably an errant mouse scroll. Thanks for the fix!
--Paul
