### ISSUE TITLE
Inaccurate pipette state after reseal completed

### ISSUE THREAD

**Issue by jessicatrnh** [acq4/acq4#157]
State field in Multipatch changes to Whole Cell instead of "Out" or In Bath to accurately reflect pipette above tissue surface.

**Comment by outofculture** [comment]
For the case where the reseal fails and times out, it will switch to "whole cell", but that choice is configurable as the `modules->MultiPatch->config->patchProfiles->*->reseal->fallbackState` value.

1 - Will setting that configuration value in the `default.cfg` file be sufficent?
2 - Is "whole cell" the wrong default choice, and should I change the default to "bath"? (i.e. will a failed reseal almost always result in the pipette just sitting out in the bath? That seems like the case to me.)
3 - When does the pipette end up in "out"? The default settings should move the pipette ~180µm back, but I don't know if that's likely to move it out of the bath.
4 - For a successful reseal, is the state going to "seal" and then "cell attached"?

**Comment by jessicatrnh** [comment]
1 - I could try that. 
2 -  It should be "bath." "Whole cell" is generally reserved for the state in which the pipette it attached to the cell (after break-in), and has free/better electrical conductance between the pipette and the cell. 
3. The pipette ends up in "out" when it is sent "home" on the XKeys, sent to "Clean". The test pulse is usually a good indicator of when the pipette is in the bath or if it is out; change in SS resistance is reflected. 
4. For a successful reseal, the state change normally is noted by the user and isn't well reflected in the software/UI...I think it would make sense to have the state change back to "seal" to reflect a GOhm seal. Another idea is to rename "reseal" to "retraction", and reassign "reseal" as the endseal after a successful experiment.

**Comment by outofculture** [comment]
2 - cool. that change is on `_staging`.
3 - okay, I can put in a "check for 'out' state" to the reseal. what should our default threshold for SS resistance be? will it max out the reading, or is it still an actual number?
4 - yeah, it looks like the reseal code is super broken and never even tries to seal. I have untested code on `_staging` for you to try out, to see if the obvious choices just work, but this might need a live coding session if it's not working out of the gate.

**Comment by jessicatrnh** [comment]
3 - I'll have to think about this a bit. The resistance value that we may want to consider for a reseal is the peak resistance. I'd like to have input from @campagnola or Tim. The SS resistance for good cells have a large range, and sometimes very high (as high as 500 MOhms), and though both types of resistances are correlated, the peak or axial resistance is often used by the operator to infer a successful reseal.

**Comment by campagnola** [comment]
I think this will be fixed by 159; let's close this and continue work there.
