### ISSUE TITLE
Add UI for editing patchpipette state parameters

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#162]
Need a way to modify state parameters in mid-experiment
- Reusable Qt elements (probably parametertree)
- Easy access from multipatch module
- Show eatch patch profile including copy-from field
- A value that is not present in config file should show up as "default" in parametertree
- Maybe allow writing config changes back to disk?

**Comment by outofculture** [comment]
* (future) pipette state machine could support save/reload
 * (future) what about keeping track of which target is associated with each pipette

**Comment by outofculture** [comment]
https://github.com/acq4/acq4/assets/28812/6b587201-1571-4749-af5b-de0fc33faccc

**Comment by campagnola** [comment]
Getting this error when trying to edit profiles:

![Image](https://github.com/acq4/acq4/assets/940580/79a49694-e78d-4940-8404-0cb8b808f6f8)

**Comment by outofculture** [comment]
pyqtgraph updated on MP0; that should fix the error.

**Comment by outofculture** [comment]
@jessicatrnh I would like to assign this ticket to you, but github won't let me

**Comment by jessicatrnh** [comment]
@outofculture no worries, I see it. I'll test this tomorrow. Thanks!
