### ISSUE TITLE
Default to mV/pA in multipatch module

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#163]
When typing in the multipatch module holding fields, if the value is initially "0 V" or "0 A", it should instead read "0 mV" or "0 pA" so that a typed value defaults to reasonable units.

**Comment by outofculture** [comment]
https://github.com/acq4/acq4/assets/28812/e952fe52-0374-48ef-b553-59cb7eaa51dd

**Comment by jessicatrnh** [comment]
After switching to IC mode, the holding field still reads "0 mV". It should be switched to "0 pA". Is that caused by this PR?

**Comment by outofculture** [comment]
If `bias` is enabled, then IC mode will still be trying to hold at some voltage, rather than current. At least, that's the behavior I've seen, but I can't say I really understand why it's happening.
