### ISSUE TITLE
Automatic tissue surface detection

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#166]
Automatically determine z-location of tissue surface

**Comment by outofculture** [comment]
New button on the Camera window, "Find Surface" (right under the "Set Surface" button). This will scan ±200µm from the currently-set surface and find the most in-focus frame to be the new surface. Let me know if it works at all, @jessicatrnh - my mock hardware was not a very good test bed for this feature.

**Comment by outofculture** [comment]
This should be testable now, with the z-stack code falling back to the slower behavior, though it won't be very fast.

**Comment by jessicatrnh** [comment]
To test, I preset the surface ~130um below where I would normally set it by eye. 

When hitting "Find Surface" the function does not work initially--the video stops acquiring and produces this error 

![Image](https://github.com/acq4/acq4/assets/43593980/cbcc2f95-01d9-4f84-9303-cef505add732)

Hitting the button again immediately starts the acquisition, but the objective overshoots the surface so that the start of the scanning range is ~70um above the actual surface. Consequently, this means that I have to preset the surface at least 200um below the actual surface to have this function work properly, otherwise the objective continues to move away from the slice indefinitely. 

I tested this again by setting my surface ~300 um below the actual surface and the objective scanned way beyond the range of 200um with an indefinite upper range, and did not detect the clearest frame.

**Comment by jessicatrnh** [comment]
image with traceback included

![Image](https://github.com/acq4/acq4/assets/43593980/9c926184-5c65-49cc-ab0a-82cd6edced2e)

**Comment by outofculture** [comment]
@jessicatrnh the bug in fast-z-stacks prevented this from being testable. with that fixed, you can try again.

**Comment by jessicatrnh** [comment]
@outofculture When I try to "Find Surface" the objective moves all the way up out of the solution, then comes down to start scanning at a range about 200um above the previously set surface marker.

**Comment by outofculture** [comment]
maybe with the focus speed fixed, this will behave? it's worth a test. if it's still doing the extraneous movement, I'll need to dig into MP0.

**Comment by jessicatrnh** [comment]
Find surface still starts well above previous surface marker (~200um) and scans upward very slowly. The objective does not scan in the +/-200um range from the previous surface marker.

**Comment by campagnola** [comment]
We also noticed: 
- Focus doesn't stop moving after clicking find surface. It ended up about 800 μm above the surface before we stopped it by `esc`.
- Focus moves very slowly. The camera was running at 20 fps and we probably only need about 5 μm accuracy here, so it should only scan about 4 seconds.

**Comment by jessicatrnh** [comment]
The "Find Surface" function now scans the depth from +200 to -200 um with reference to the previously set surface, but does not indicate if the surface has been found; it just stops at -200 below previous surface.

**Comment by outofculture** [comment]
I just added a final "focus to the new surface depth" step to the button behavior. If it doesn't find a new surface, it will stay at the bottom of the scan, as before. I tested the rest of the algorithm, and it found the surface on the few test files I have, but if you run it on a slice and it doesn't find a surface, please save a ±200µm, top-down z-stack for me to test against.

**Comment by jessicatrnh** [comment]
Scans the depth range but does not return anything for surface detection. Stack is saved in autopatch_test\2024.03.12_000\Surface_Finder_Stack

**Comment by outofculture** [comment]
okay, it should do more than just scan this time.

**Comment by jessicatrnh** [comment]
@outofculture So it does. The feature scans from +200 to -200 microns from the previously set surface. However, the correct surface is not detected and the surface marker is now reset to the bottom of the range.

**Comment by outofculture** [comment]
and again!

**Comment by jessicatrnh** [comment]
@outofculture This works now! behavior: scans the 400um range and resets and focuses on surface depth. Might be about -25um from where I would consider the surface to be but this is working.

**Comment by jessicatrnh** [comment]
related to ticket #241

**Comment by campagnola** [comment]
Observations today:
- Find a random target needs to be able to switch between brightfield for surface detection and fluorescence for cell detection
- this was failing silently; make sure errors are visible to user

**Comment by outofculture** [comment]
swallowed error should be exposed now
