### ISSUE TITLE
Add mechanism to automatically reload slice images to camera module

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#167]
It would be nice if we can reload the camera module's pinned images from disk after restarting acq4. Possible mechanisms:
- "pin selected images" button in camera module that loads files selected in dta manager module
- "reload previous state" button in manager that automatically reloads previous state on shutdown (for example, pined images, loaded modules, window positions, etc.). Modules could provide saveState / loadState methods to support this.
- "restart acq4" button in manager module that does an automatic save, quit, restart, reload

**Comment by outofculture** [comment]
* a "sync with data dir" toggle that always saves/loads pinned frames whenever the data directory is changed

**Comment by outofculture** [comment]
relevant architecture:

![Image](https://github.com/acq4/acq4/assets/28812/621dcbf2-6676-4e71-8729-b72d9ac2824b)

**Comment by outofculture** [comment]
notes: included in this ticket is the intention that we make the Frame object carry all the necessary information to render the image on the screen, which means the bg subtraction, contrast controls and transform all need to be present. that way, pinned frames can be identical to how the user sees them.

**Comment by outofculture** [comment]
More todo:
 - record the name of the imaging device in the frame info
 - teach CameraWindow to give back the interface for a given device name

**Comment by outofculture** [comment]
@jessicatrnh here's a new feature for you. any images you've saved can now be loaded back into the camera. The new button is currently all the way to the right on the Data manager:

![Image](https://github.com/acq4/acq4/assets/28812/de7669ec-451c-486d-a44d-b014d8e6597c)

...but let me know if it would make more sense elsewhere. that button should only be enabled when your current storage directory contains images. primary use-case is probably to make it less disruptive to restart ACQ4 mid-experiment; while old slice images _can_ be re-pinned, I'm not sure why you would want that. Background subtraction and the "Display Control" contrast adjustments should also be preserved on all future saved images, e.g. they shouldn't be dim.
