### ISSUE TITLE
PatchPipette "fouled" flag should reset after cleaning

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#168]
Currently, the "fouled" flag seems to persist after cleaning (although it's possible this could happen for experimental rather than software reasons)

**Comment by outofculture** [comment]
This seems to have only been a bug in the ui; the pipette state was being updated correctly already, which was reflected in its ability to be fouled again a second time later. The ui should accurately reflect the pipette state now.

**Comment by jessicatrnh** [comment]
'Fouled' unchecked after cleaning completed.
