### ISSUE TITLE
Fast z-stacks

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#171]
We need to be able to collect image z-stacks more quickly--current approach is to step the z stage, take a frame, and repeat. 
Better approach is to have the z stage move continuusly while streaming from the camera, but we need some way to characterize the lag in frame / position updates. Take the z stack in both directions and look for hysteresis?

- [x] Create FrameAcquisitionFuture that just handles collecting frames in a background thread
- [x] Make CameraTask use FrameAcquisitionFuture
- [x] Put all camera control outside of AcquireFramesFuture
- [x] (maybe) include camera control, taking that over from CameraTask
- [x] Move camera module sequencing code to util/imaging/sequencer
- [x] Add a function getZStack(imager, params) that returns a future containing the thread acquiring a z stack
- [x] Add Microscope.getZStack as a convenience
- [x] Make pipette tracker use fast z scan in place of its existing takeReferenceFrames method

**Comment by outofculture** [comment]
would adding timing flashes from a light source improve the situation?

**Comment by outofculture** [comment]
Oh, or maybe this is something that just needs to be calibrated. It could happen somewhat automatically with a 3D object in frame (do old-style z-stack and fast-style z-stack, then find the adjustment needed to line them up).

**Comment by outofculture** [comment]
Z-stacks should be much faster now. In the Camera window:

![Image](https://github.com/acq4/acq4/assets/28812/15d34381-b3ec-4038-8a2a-d25f782f0aef)

Select the camera, configure a z-stack, and hit "Start". This should save a z-stack into the currently selected data directory. This should lock the focus and camera devices for the duration. Attn @jessicatrnh - give this a shot and let me know if it works. Again, my mock hardware doesn't offer a good way to test this for real world behavior. This is the same code being used by the "Find Surface" button, so bugs for this may show up there, as well.

**Comment by outofculture** [comment]
The scientifica focus controller on MP0 is wonky and isn't listening to speed settings, which is a fundamental requirement for the fast z-stack feature. I gave this fall-back behavior to slow z-stack code, so it should at least still function on MP0.

**Comment by jessicatrnh** [comment]
@outofculture I received this error when trying to record the stack. I checked the box, set the start position at the surface and end position ~ 100um below the start position. The objective did not move and the video stopped acquiring. 


![Image](https://github.com/acq4/acq4/assets/43593980/ddec5b80-a05f-4a39-abc7-1f4f94efa7bd)

**Comment by jessicatrnh** [comment]
Traceback for error message above:


![Image](https://github.com/acq4/acq4/assets/43593980/b8ce77a7-1b23-4155-bf61-2a1f8eba487c)

**Comment by outofculture** [comment]
I had only tested it with the camera off at the start. good, good. I tested it on MP0 both ways this time, so it shouldn't be broken this time.

**Comment by jessicatrnh** [comment]
z stacks are working and moving faster...about 2um/sec
