### ISSUE TITLE
Auto collect tiled mosaic

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#203]
Some way to automatically collect a tiled mosaic covering an entire slice
- ~Autofocus~
- ~Find boundaries~
- Fill mosaic
- Store as one .ma file or one folder full of images
- Metadata: which slice is this a picture of?

**Comment by campagnola** [comment]
As part of this, the image sequencer used to collect Z stacks should be extended to allow xy mosaics as well. Ideally it should be possible to take a z stack at each location as well.
It probably won't be useful to try to do fast xy scanning the same way we collect fast z stacks.

**Comment by outofculture** [comment]
* make a shared api for CameraInterface and Camera(Device) that can be passed into the sequencer or anywhere else that wants Frames.
* teach Frame to append to an existing file.
* put the background-saving logic into a Frame object.
* fix the background-saving bug that would occur if two images got saved into different folders that nevertheless share a background.
