### ISSUE TITLE
holding potential not recorded by multiclamp module

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#206]
When plotting the holding potential in the multiclamp module, values are all zero and do not reflect the actual holding potential.

**Comment by jessicatrnh** [comment]
@outofculture I still do not see that this is reflected correctly 


![Image](https://github.com/acq4/acq4/assets/43593980/eac7942a-d40b-40d2-a4c1-30d4071a8a6d)

**Comment by jessicatrnh** [comment]
now being recorded
