### ISSUE TITLE
Seal mode bugs

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#212]
Some bugs encountered in seal mode that may or may not be related:
- When crossing the 100 MΩ threshold, holding should switch to -70 mV. Sometimes this doesn't happen, and it may be related to the auto bias being on or off.
- When crossing the 1 GΩ threshold, sometimes the state doesn't transition to cell attached

Related: I think the auto bias button should not affect the holding potential when in VC mode, but currently that might not be the case. The options while in VC should be: 
- "off" -> no auto bias is applied when switching to IC
- "VC" -> when switching to IC, the VC holding potential is used as the initial auto bias value
- "manual"  (maybe?)  user manually sets the auto bias value

**Comment by jessicatrnh** [comment]
This is related to task #208

**Comment by jessicatrnh** [comment]
Noted issues with seal feature 02/27/2024

**Comment by jessicatrnh** [comment]
Still seeing issues with -1kPa not being applied continuously when seal function is enabled.

**Comment by outofculture** [comment]
Issues aren't seen when seals happen quickly. Workaround is to re-enter Seal mode multiple times. Holding gets turned off completely if seal fails. Test pulse analysis needs to be improved to better handle "next state" behavior. The switching to Atmosphere is the worst of the current behaviors.

**Comment by campagnola** [comment]
Only thing left here: prematurely switching to whole cell immediately after cell attached (maybe a capacitance issus)

**Comment by jessicatrnh** [comment]
Still seeing "incorrect" state after successful seal. State switched quickly through cell-attached in to "whole-cell" even when SSR >> 1gigaohm. 
see log in autopatch_test\2024.06.11_000\slice_000\cell_002

**Comment by jessicatrnh** [comment]
The seal feature seems to foul or time out during the iteration of -1 to -3kPa applicaton. E.g. during a seal, it will go from -1kPa to -3kPa, switch to Atmosphere, then start the gradual pressure application but reaches -1.7kPa and switches to "fouled". Values of where it fouls out varies, and I'm not sure why it stops mid suction.

**Comment by campagnola** [comment]
This sounds normal -- if cell sealing times out, then the pipette is marked fouled. We can adjust the timeout duration, but usually it is easier to just clean and try another.

**Comment by jessicatrnh** [comment]
Yes, I think adjusting the timeout duration will make sense. I can do that in the config. file.
