### ISSUE TITLE
look at autofocus to see how to get 20µm higher

### ISSUE THREAD

**Issue by outofculture** [acq4/acq4#241]

**Comment by jessicatrnh** [comment]
still focused a bit below surface. Can we try 92%?

**Comment by outofculture** [comment]
Ooo, even better, to let you play with it directly, I added a new config option:

```
Microscope:
    surfaceDetectionPercentileThreshold: 92
```

**Comment by jessicatrnh** [comment]
#need to test different values. From 96-->92 results in surface to be detected -40um below actual surface.

**Comment by jessicatrnh** [comment]
I would expect surface detection to improve when decreasing the percentile threshold. The higher the percentage the better, but not a significant decrease in difference between detected surface and user-identified surface. Currently set to 99.9999 but delta still ~20um

**Comment by outofculture** [comment]
yep, I was going backwards in my math. this should get you better results (though I needed to set my percentile to 90 to get frame 360 on the test stack).

**Comment by jessicatrnh** [comment]
@outofculture code changes for this are on the rig! argmax is changed to argwhere. The code is working now and the surface is detected where it needs to be.
