### ISSUE TITLE
Imager does not open but fails with error in dockarea

### ISSUE THREAD

**Issue by mgraupe** [acq4/acq4#26]
The imager gui fails to open but aborts with the following error message:

AttributeError: 'NoneType' object has no attribute 'insert'
  File "acq4\modules\Manager\Manager.py", line 91, in loadModule
    self.manager.loadDefinedModule(mod)
  File "acq4\Manager.py", line 579, in loadDefinedModule
    mod = self.loadModule(mod, mName, config, forceReload=forceReload)
  File "acq4\Manager.py", line 512, in loadModule
    mod = modclass(self, name, config)
  File "acq4\modules\Imager\Imager.py", line 340, in __init__
    self.manager.loadDefinedModule(config['cameraModule'])
  File "acq4\Manager.py", line 579, in loadDefinedModule
    mod = self.loadModule(mod, mName, config, forceReload=forceReload)
  File "acq4\Manager.py", line 512, in loadModule
    mod = modclass(self, name, config)
  File "acq4\modules\Camera\Camera.py", line 10, in __init__
    self.ui = CameraWindow(self)
  File "acq4\modules\Camera\CameraWindow.py", line 122, in __init__
    self.cw.restoreState(uiState['docks'], missing='ignore')
  File "acq4\pyqtgraph\dockarea\DockArea.py", line 250, in restoreState
    a.addDock(d, 'below')
  File "acq4\pyqtgraph\dockarea\DockArea.py", line 112, in addDock
    old.apoptose()
  File "acq4\pyqtgraph\dockarea\Container.py", line 65, in apoptose
    cont.apoptose()
  File "acq4\pyqtgraph\dockarea\Container.py", line 65, in apoptose
    cont.apoptose()
  File "acq4\pyqtgraph\dockarea\Container.py", line 65, in apoptose
    cont.apoptose()
  File "acq4\pyqtgraph\dockarea\Container.py", line 61, in apoptose
    self.container().insert(self.widget(0), 'before', self)

Removing the recent changes from acq4/pyqtgraph/dockarea/DockArea.py resolves this issues. 

Cheers,
Michael

**Comment by campagnola** [comment]
Strange, I didn't have this problem..
Can you post your `acq4/config/modules/Camera_0_ui.cfg` (which stores the window and dock configuration) ? 

Deleting this file should resolve the issue as well, but let me know if it doesn't.

**Comment by mgraupe** [comment]
When I delete `acq4/config/modules/Camera_ui.cfg` the Imager module opens without error in a default state. After customizing the window arrangement and closing the Camera window, I get the following error:
------------

2015.06.29 13:27:03 Unexpected error: 
TypeError: QMainWindow.closeEvent() is a private method
TypeError: QMainWindow.closeEvent() is a private method
  File "acq4\pyqtgraph\dockarea\DockArea.py", line 348, in closeEvent
    QtGui.QMainWindow.closeEvent(self, *args, **kwargs)

-------------

However, deleting the file did resolve the issue of not being able to open the Imager module. 

Cheers,
Michael

**Comment by campagnola** [comment]
Aha, it looks like this happens if you try to close a floating dock (if you embed the docks inside the camera window, the error should go away). I'll see about a fix..

**Comment by mgraupe** [comment]
That is probably the explanation. I have the Camera control window
separated from the Display window.

Thanks,
Michael

On Mon, Jun 29, 2015 at 9:46 PM, Luke Campagnola <notifications@github.com>
wrote:

> Aha, it looks like this happens if you try to close a floating dock (if
> you embed the docks inside the camera window, the error should go away).
> I'll see about a fix..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acq4/acq4/issues/26#issuecomment-116814599>.
>



-- 
Michael Graupner (PhD)
Brain Physiology Lab, Université Paris Descartes
http://www.biomedicale.parisdescartes.fr/~mgraupe/
michael.graupner@parisdescartes.fr

**Comment by mgraupe** [comment]
However, I would like to add that this error did not occur before the
recent changes to DockArea.py . The Camera window closes without error
message if I revert to the previous version of DockArea.py.

Cheers,
Michael

On Mon, Jun 29, 2015 at 9:48 PM, Michael Graupner <
michael.graupner@parisdescartes.fr> wrote:

> That is probably the explanation. I have the Camera control window
> separated from the Display window.
>
> Thanks,
> Michael
>
> On Mon, Jun 29, 2015 at 9:46 PM, Luke Campagnola <notifications@github.com
> > wrote:
>
>> Aha, it looks like this happens if you try to close a floating dock (if
>> you embed the docks inside the camera window, the error should go away).
>> I'll see about a fix..
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/acq4/acq4/issues/26#issuecomment-116814599>.
>>
>
>
>
> --
> Michael Graupner (PhD)
> Brain Physiology Lab, Université Paris Descartes
> http://www.biomedicale.parisdescartes.fr/~mgraupe/
> michael.graupner@parisdescartes.fr
>
>


-- 
Michael Graupner (PhD)
Brain Physiology Lab, Université Paris Descartes
http://www.biomedicale.parisdescartes.fr/~mgraupe/
michael.graupner@parisdescartes.fr

**Comment by campagnola** [comment]
I believe this is fixed in the latest commit. Please reopen if that turns out to be untrue..
