### ISSUE TITLE
Obstacle avoidance during cell detection

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#263]
When approaching a cell through tissue, the operator usually watches the pipette tip for contact with any obstacles hit before reaching the cell. This is most apparent when the tip is blocked, causing the pressure wave to dissipate from the surrounding tissue. For automation, though, it is easier to just watch for changes in resistance. So, in cell-detect mode:
 - Advance toward the cell while monitoring resistance
 - If resistance increases beyond a threshold before reaching the cell, move back about 10 μm and check that the resistance recovered (if it doesn't, then the tip is fouled)
 - Move the pipette 5-10 μm laterally to avoid the obstacle, then advance 20 μm and return to the original axial path to the target

**Comment by outofculture** [comment]
@jessicatrnh okay, to test this, you'll want to look at the following 'cell detect' parameters:

- obstacleDetection : bool
  -  If True, sidestep obstacles (default False)
- obstacleRecoveryTime : float
  - Time (s) allowed after retreating from an obstacle to let resistance to return to normal (default 1 s)
- obstacleResistanceThreshold : float
  - Resistance (Ohm) threshold above the initial resistance measurement for detecting an obstacle (default 1 MOhm)
- sidestepLateralDistance : float
  - Distance (m) to sidestep an obstacle (default 10 µm)
- sidestepBackupDistance : float
  - Distance (m) to backup before sidestepping (default 10 µm)
- sidestepPassDistance : float
  - Distance (m) to pass an obstacle (default 20 µm)
- minDetectionDistance : float
  - Minimum distance (m) from target before cell detection can be considered (default 50 µm)

**Comment by outofculture** [comment]
oh, and it won't avoid obstacles if it is minDectectionDistance away from the target.

**Comment by jessicatrnh** [comment]
```
2024-07-24T14:31:49.221771-07:00 Unexpected error: 
AttributeError: 'PatchPipette' object has no attribute 'patchrec'
AttributeError: 'PatchPipette' object has no attribute 'patchrec'
  File C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\states.py, line 217, in _runJob
    self.nextState = self.run()
                     ^^^^^^^^^^
  File C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\states.py, line 643, in run
    return self._run()
           ^^^^^^^^^^^
  File C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\states.py, line 651, in _run
    return self._transition_to_seal(speed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\states.py, line 754, in _transition_to_seal
    self.dev.patchrec()['detectedCell'] = True
    ^^^^^^^^^^^^^^^^^

Show thread states 59
```

**Comment by jessicatrnh** [comment]
Pipette approaches target as expected but state quickly changes to seal or foul states immediately when the tip touches the tissue...

**Comment by jessicatrnh** [comment]
Working much better after changing the cell detect advanceSpeed from 10um/s to 5um/s. The pipette avoided the obstacle (moved around it!) but the target still needs some fine tuning (either drift or distance too far).

**Comment by campagnola** [comment]
Some things to add here:
- speed should decrease as we approach the cell (maybe 20um/s outside tissue, 5um/s after crossing the surface, 2 um/s once we are within 15 um of the cell)
- even if an obstacle is not detected, do something to shrug off potential snags, like: stop, reverse 5 um, wiggle briefly, continue on. Do this once at 20 um from the cell and again at 10 um.
