### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by JNCronk** [acq4/acq4#279]
Hi,

After installing acq4 runs into problems on startup:

`/Users/justin/acq4/acq4/util/debug.py:43: RuntimeWarning: Error loading file type library 'MultiPatchLog':
Traceback (most recent call last):
`
...
I think the route cause being

`from neuroanalysis.test_pulse_stack import H5BackedTestPulseStack
ModuleNotFoundError: No module named 'neuroanalysis.test_pulse_stack'`

I have, I believe all the requirements, but can't seem to find this module within neuroanlysis.

Any thoughts would be greatly appreciated.

**Comment by campagnola** [comment]
Greetings, this is our fault -- we have been making improvements to the test pulse analysis system and now depend on some features of neuroanalysis that haven't been released yet. We should have this fixed soon.

 @outofculture maybe you can suggest a quick solution?

**Comment by outofculture** [comment]
Oh my! Yes, the neuroanalysis PR that adds that hasn't been accepted yet. In the mean time, you can install in from my github branch `pip install git+https://github.com/outofculture/neuroanalysis.git@can-we-pass`. I'll hopefully have that merged and released in the next week or two, and then the install will go much more smoothly.

**Comment by JNCronk** [comment]
Perfect, thanks. Great stuff your doing here!

**Comment by outofculture** [comment]
I released neuroanalysis 0.0.3 which should behave with the main ACQ4 branch. Let us know if you have any more troubles.
