### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by outofculture** [acq4/acq4#76]
https://www.python.org/doc/sunset-python-2/

**Comment by outofculture** [comment]
I'm not there yet, but [this branch](https://github.com/outofculture/acq4/tree/toward-python3) will hopefully become a PR soon.

**Comment by outofculture** [comment]
It bears mentioning that at least micromanager still doesn't run under python3, so we won't be able to drop compatibility with python2 as part of this work.

**Comment by berl** [comment]
@outofculture have you tried the pymmcore that has been broken out of micromanager?  https://github.com/micro-manager/pymmcore
It's supposed to be the official route for python 3 compatibility, but I haven't tested it.

**Comment by outofculture** [comment]
@berl no! I'll give it a whirl, thanks! (:crossed_fingers:)

**Comment by outofculture** [comment]
I've been using python3 successfully in production for a while now. We probably need testing done on more diverse hardware before this can be considered successful. Can anyone else report on whether the python3 branch is functional, and on what hardware? For my own testing, I've seen success with:

* a few µManager-compatible cameras
* Sensapex stage, manipulators and pressure control
* nidaq and multiclamp 700B
* zeiss microscope parts

The branch has setup and installation instructions in its README.md.

( I should warn that camera fps gets hit hard by the switch to python3, and I've been using pyqtgraph's new CUDA processing feature to speed that up, though that requires an nvidia gpu. #109 has that work. )

**Comment by berl** [comment]
I've been running this branch successfully for a bit with our `mfishacq4` module which includes
- a µManager Hamamatsu Flash4v3 camera, ASI stage, Lumencor light engine and Olympus microscope (µManager2.0gamma and `pymmcore`)
- a fluidics system including an Ismatec peristaltic pump and multiple Elveflow valve switchers- these are all serial devices.
- a zeromq relay module to handle a few external protobuf commands

This doesn't expand the hardware base much, but I hope it helps. 
Other notes:
- I also had an acquisition problem show up in my python3 deployment related to extra frames on my camera, but it could related to the DCAM driver, µManager module or python 3. 
-  Other code changes included:
  -- string encoding for the serial commands
  -- fixing various `Qt` imports
  -- some changes with QThreads whereby if a running QThread was deleted while running (e.g. in a sloppy shutdown of a device) acq4 would completely crash.  same code didn't have a problem in python2.
